%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Initialize some environment variables, parameters
% and other stuffs for the algorithm.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% path to MatlabBGL
addpath('./matlab_bgl/');
addpath('./dataMatlab');

% path to input files
%INPUT = struct( 'users', './data/EXTRACTED_USERS.tsv', ...
%                'items', './data/ITEM.tsv', ...
%                'logtrain', './data/REC_LOG_TRAIN.tsv', ...
%                'action', './data/USER_ACTION.tsv', ...
%                'keyword', './data/USER_KEY_WORD.tsv', ...
%                'profile', './data/USER_PROFILES.tsv', ...
%                'sns', './data/USER_SNS.tsv');

PARAMS = struct( 'itemDistanceWeight', 0.5, ...
                'userDistanceWeight', 0.5);
load('items.mat');
load('users.mat');